### PR TITLE
Configurable Classes

### PR DESCRIPTION
**Pull request by Jador**
This is intended to solve #12 

Each class name in the code base is now configurable via props ([much like](https://facebook.github.io/react/docs/animation.html#custom-classes))

This has the nice side effect of fully supporting [CSS Modules](https://github.com/css-modules/css-modules)

I also went ahead and added the `onlyClasses` prop discussed in the issue

### CODE REVIEW

**Comment by Jador** [comment]
Also plan to tackle #11 if this looks good and add new docs then

**Comment by burakcan** [comment]
@fatiherikli @strada can you take a look, pls?

**Comment by burakcan** [comment]
@Jador thank you :100: :)
can you please pull the current state of the master, since it looks like there are conflicts with your's.

**Comment by Jador** [comment]
@burakcan should be good

**Pull request merged**
