### PR TITLE
Added a distinciton between isPassive and dates that are outside the min/max date

### PR DESCRIPTION
**Pull request by mimshwright**
Basically this should allow you to style days that are outside of min/max differently from dates that are outside the current month. Dates outside of min/max also have isPassive prop so this shouldn't break anything, only add the extra customization.

### CODE REVIEW

**Comment by mimshwright** [comment]
Added Finnish language support.

**Comment by mimshwright** [comment]
Added a fix for #124 which allows you to specify whether to show days in current month.

**Comment by mimshwright** [comment]
I'm going to branch this properly so that each feature can be pulled in individually.

**Comment by manjunath-teachmint** [comment]
is this merged?

**Pull request closed without merging**
