### PR TITLE
Added custom placeholder for date ranges display.

### PR DESCRIPTION
**Pull request by jeromemmiranda**
## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description
Allow to pass custom placeholder for date ranges display. I've retain the defaults "Early" and "Continuous" if the placeholders were not provided.

> Related Issue: #292

### CODE REVIEW

**Comment by jeromemmiranda** [comment]
Is this plugin still being maintain?

**Comment by keremciu** [comment]
@jeromemmiranda yes, actually @mkg0 is the core contributor for the next version but I will take a look to this one to merge

**Comment by jeromemmiranda** [comment]
@keremciu great, thanks for that. This plugin is really helpful.
Also, do you accept donations? If yes, can you provide link.

**Comment by SteveJRobertson** [comment]
Hi, any word on this getting merged? I really like the functionality but I need to be able to change the placeholder text.

**Comment by keremciu** [comment]
HI guys, I will take care of PRs, I was so busy by finding a new job stuff, I will gonna spend a day to review them :)

**Comment by onurkerimov** [comment]
The related issue is resolved in the latest release. (1.0.1) I couldn't merge your PR, since I have seen it after I was already working on it and after changing the file structure of the project. I'm closing this. Thank you for working on this.

**Pull request closed without merging**
