### PR TITLE
Arbitrary Disabling of Days

### LINKED ISSUE #11: Ability to color some specific dates or date ranges

### PR DESCRIPTION
**Pull request by Jador**
To resolve some of the points in #11

By default the calendar will disable days that fall out of the month.

This PR introduces `minDate`, `maxDate`, and `disableDay`

min and max date, when provided, override the default behavior (i.e instead of minDate being the first of the month it is whatever date is specified).

`disableDay` trumps all (i.e min/max date are ignored if disableDay is provided). It is a predicate function of (moment) => boolean. If the function returns true for the given day it will be disabled.

There may be some other niceties that might want to be added to this, but this should be flexible enough to handle any case that may arise.

### CODE REVIEW

**Comment by Jador** [comment]
Started working on this and went ahead and created the PR so I can get some feedback as I'm writing it.

I know...the diff...it'll be better when #17 is accepted =^.^=

**Comment by Jador** [comment]
Decided to work multi day/range select in another branch.

**Comment by burakcan** [comment]
@Jador is this still wip or ready to merge?

**Comment by Jador** [comment]
Everything is pushed up.

There is one case that isn't being handled very well imo. Right now you can select a range that spans over a disabled day. I think in that case it should cancel the selection. What do you think?

Either way, that could be done in another PR

**Comment by burakcan** [comment]
Thanks @Jador 

> There is one case that isn't being handled very well imo. Right now you can select a range that spans over a disabled day. I think in that case it should cancel the selection. What do you think?

I think its better to not to introduce `disableDay` feature for now because it'll be "multi range™" and it'll add a lot of complexity to the code and usage.

**Comment by Jador** [comment]
You've got it

**Comment by GregTheGreek** [comment]
did `disableDay` ever get implemented ?

**Pull request closed without merging**
