### PR TITLE
allow Day cells to have margin

### PR DESCRIPTION
**Pull request by stijndeschuymer**
Hi, great work on this component!
I would like to be able to add 'margin' to the Day Cells.
This PR makes it possible

Thanks!

### CODE REVIEW

**Comment by burakcan** [comment]
@strada @fatiherikli taking this in?

**Comment by fatiherikli** [comment]
looks good :+1:

**Comment by burakcan** [comment]
Thank you @stijndeschuymer :+1:

**Comment by stijndeschuymer** [comment]
My pleasure, thank you guys!

**Pull request merged**
