### PR TITLE
Use prop-types instead of React.PropTypes

### PR DESCRIPTION
**Pull request by kazazor**
* Updated PropTypes usage to remove react warnings for 15.5.x
* Remove the `lib` folder from the repo (it shouldn't be there.. You get it by running `npm run build`

Resolves https://github.com/Adphorus/react-date-range/issues/130

### CODE REVIEW

**Comment by burakcan** [comment]
Will publish this tomorrow.

**Comment by kazazor** [comment]
Great @burakcan ! Will wait for your publishing today so we could stop getting these errors..

**Comment by ninahaack** [comment]
I'm waiting too :]

**Comment by burakcan** [comment]
Published it yesterday

**Pull request merged**
